config/routes.rb
Rails.application.routes.draw do
  mount Bulkrax::Engine, at: '/'
  mount Riiif::Engine => 'images', as: :riiif if Hyrax.config.iiif_image_server?
  mount BrowseEverything::Engine => '/browse'

  resources :other_options, only: [:destroy]

  concern :oai_provider, BlacklightOaiProvider::Routes.new

  concern :range_searchable, BlacklightRangeLimit::Routes::RangeSearchable.new
  get '/downloads/:id(.:format)', to: 'scholars_archive/downloads#show', as: 'download'
  get '/single_use_link/download/:id(.:format)', to: 'scholars_archive/single_use_links_viewer#download', as: 'download_single_use_link'
  get '/dashboard/shares(.:format)', to: 'scholars_archive/shares#index', as: 'dashboard_shares'
  mount Blacklight::Engine => '/'
  mount BlacklightAdvancedSearch::Engine => '/'


  concern :searchable, Blacklight::Routes::Searchable.new

  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :oai_provider
    concerns :searchable
    concerns :range_searchable
  end

  devise_for :users

  # For Sidekiq administration UI
  authenticate :user, ->(u) { u.admin? } do
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end


  mount Hydra::RoleManagement::Engine => '/'
  mount Qa::Engine => '/authorities'
  mount Hyrax::Engine, at: '/'
  resources :welcome, only: 'index'
  root 'hyrax/homepage#index'
  curation_concerns_basic_routes
  concern :exportable, Blacklight::Routes::Exportable.new

  get '/xmlui', to: 'hyrax/homepage#index'
  get '/xmlui/handle/:handle_prefix/:handle_localname/:action', to: 'scholars_archive/handles#handle_show', as: 'handle_show_action'
  get '/xmlui/handle/:handle_prefix/:handle_localname', to: 'scholars_archive/handles#handle_show', as: 'handle_show'
  get '/xmlui/bitstream/handle/:handle_prefix/:handle_localname/:file(.:format)', to: 'scholars_archive/handles#handle_download', as: 'handle_download_handle', file: /.*?/, format: /[^.]+/
  get '/xmlui/bitstream/:handle_prefix/:handle_localname/:sequence_id/:file(.:format)', to: 'scholars_archive/handles#handle_download', as: 'handle_download', file: /.*?/, format: /[^.]+/
  get '/xmlui/*path', to: 'hyrax/homepage#index'

  get '/jspui', to: 'hyrax/homepage#index'
  get '/jspui/handle/:handle_prefix/:handle_localname/:action', to: 'scholars_archive/handles#handle_show', as: 'handle_show_action_jspui'
  get '/jspui/handle/:handle_prefix/:handle_localname', to: 'scholars_archive/handles#handle_show', as: 'handle_show_jspui'
  get '/jspui/bitstream/handle/:handle_prefix/:handle_localname/:file(.:format)', to: 'scholars_archive/handles#handle_download', as: 'handle_download_handle_jspui', file: /.*?/, format: /[^.]+/
  get '/jspui/bitstream/:handle_prefix/:handle_localname/:sequence_id/:file(.:format)', to: 'scholars_archive/handles#handle_download', as: 'handle_download_jspui', file: /.*?/, format: /[^.]+/
  get '/jspui/*path', to: 'hyrax/homepage#index'

  get '/dspace', to: 'hyrax/homepage#index'
  get '/dspace/handle/:handle_prefix/:handle_localname', to: 'scholars_archive/handles#handle_show', as: 'handle_show_dspace'
  get '/dspace/bitstream/handle/:handle_prefix/:handle_localname/:sequence_id/:file(.:format)', to: 'scholars_archive/handles#handle_download', as: 'handle_download_dspace_handle', file: /.*?/, format: /[^.]+/
  get '/dspace/bitstream/:handle_prefix/:handle_localname/:sequence_id/:file(.:format)', to: 'scholars_archive/handles#handle_download', as: 'handle_download_dspace', file: /.*?/, format: /[^.]+/
  get '/dspace/*path', to: 'hyrax/homepage#index'

  get '/mla/:id', to: 'scholars_archive/citations#mla', as: 'mla'
  get '/apa/:id', to: 'scholars_archive/citations#apa', as: 'apa'
  get '/chicago/:id', to: 'scholars_archive/citations#chicago', as: 'chicago'

  patch '/contentblock/update/:name', to: 'scholars_archive/content_blocks#update', as: 'update_content_blocks'

  resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable
    collection do
      delete 'clear'
    end
  end

  # CUSTOM ROUTES #1: Routes to deletion of all file sets
  namespace :hyrax, path: :concern do
    concerns_to_route.each do |curation_concern_name|
      namespaced_resources curation_concern_name, only: [] do
        member do
          delete :destroy_all_files
        end
      end
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # ACCESSIBILITY REQUEST FORM ROUTE: Setup the routes for the accessibility form
  get 'accessibility_request', to: 'scholars_archive/accessibility_request_form#new', controller: 'scholars_archive/accessibility_request_form'
  post 'accessibility_request', to: 'scholars_archive/accessibility_request_form#create', as: :accessibility_request_form_index, controller: 'scholars_archive/accessibility_request_form'

  # bot detection challenge
  get "/challenge", to: "bot_detection#challenge", as: :bot_detect_challenge
  post "/challenge", to: "bot_detection#verify_challenge"
end

app/models/concerns/scholars_archive/article_metadata.rb
# frozen_string_literal: true

module ScholarsArchive
  # article metadata
  module ArticleMetadata
    extend ActiveSupport::Concern

    # Usage notes and expectations can be found in the Metadata Application Profile:
    #   https://docs.google.com/spreadsheets/d/1koKjV7bjn7v4r5a3gsowEimljHiAwbwuOgjHe7FEtuw/edit?usp=sharing

    included do
      property :editor, predicate: ::RDF::Vocab::BIBO.editor do |index|
        index.as :stored_searchable
      end

      property :has_journal, predicate: ::RDF::URI.new('http://purl.org/net/nknouf/ns/bibtex#hasJournal'), multiple: false do |index|
        index.as :stored_searchable, :facetable
      end

      property :has_number, predicate: ::RDF::URI.new('http://purl.org/net/nknouf/ns/bibtex#hasNumber'), multiple: false do |index|
        index.as :stored_searchable
      end

      property :has_volume, predicate: ::RDF::URI.new('http://purl.org/net/nknouf/ns/bibtex#hasVolume'), multiple: false do |index|
        index.as :stored_searchable
      end

      property :web_of_science_uid, predicate: ::RDF::URI.new('http://opaquenamespace.org/ns/webOfScienceUid'), multiple: false do |index|
        index.as :stored_searchable
      end
    end
  end
end

app/models/concerns/scholars_archive/date_operations.rb
# frozen_string_literal: true

module ScholarsArchive
  # date ops for form
  module DateOperations
    extend ActiveSupport::Concern

    # rubocop:disable Lint/ShadowedArgument
    def to_solr(solr_doc = {})
      solr_doc = super
      solr_doc = solr_doc.merge({ 'date_decades_ssim' => decades })
      solr_doc.merge({ 'date_facet_yearly_ssim' => date_facet_yearly })
    end
    # rubocop:enable Lint/ShadowedArgument

    # date_facet_yearly is intended to be used for date_facet_yearly_ssim, which is used by the facet provided
    # by the interactive Blacklight Range Limit widget
    # date_facet_yearly is expected to return an array of yearly date values like [1910, 1911, 1912]
    # If given date_value = invalid date, i.e. "typo_here2011-12-01", we will get nil
    def date_facet_yearly
      return nil if yearly_dates.empty?

      yearly_dates
    rescue ArgumentError => e
      Rails.logger.warn e.message
      nil
    end

    # decades is intended to be used for date_decades_ssim, which is used by the decade facet
    # decades is expected to return an array of year ranges like ["1910-1919", "1920-1929"]
    # here are some examples:
    #  a) given date_value = "2017-12-01", we will get ["2010-2019"]
    #  b) given date_value = "2017-12", we will get ["2010-2019"]
    #  c) given date_value = "2017", we will get ["2010-2019"]
    #  d) given date_value = "2017-2018", we will get ["2010-2019"]
    #  e) given date_value = "2010-2020", we will get ["2010-2019", "2020-2029"]
    #  f) given date_value = "1900-1940", we will get nil
    #  g) given date_value = invalid date, i.e. "typo_here2011-12-01", we will get nil
    def decades
      return nil if decade_dates.empty?

      decade_dates.map(&:decade)
    rescue ArgumentError => e
      Rails.logger.warn e.message
      nil
    end

    # Determine the date value to use for Decades facet and date facet yearly processing.
    def date_value
      if date_created.present?
        date_created
      elsif date_copyright.present?
        date_copyright
      elsif date_issued.present?
        date_issued
      end
    end

    # yearly_dates returns an array of years given a valid date_value. Here are some examples:
    #  a) given date_value = "2017-12-01", we will get [2017]
    #  b) given date_value = "2017-12", we will get [2017]
    #  c) given date_value = "2017", we will get [2017]
    # it also works with ranges and special dates in the ISO 8601 format:
    #  d) given date_value = "2017-12-01/2019-12-01", we will get [2017, 2018, 2019]
    #  e) given date_value = "2017-12/2019-12", we will get [2017, 2018, 2019]
    #  f) given date_value = "2017/2019", we will get [2017, 2018, 2019]
    def yearly_dates
      date_value ? clean_years : []
    end

    def clean_years
      date = Date.edtf(date_value)
      if date.instance_of? EDTF::Interval
        date.map(&:year).uniq
      elsif date.instance_of? Date
        Array.wrap(date.year)
      else
        parsed_year ? Array.wrap(parsed_year) : []
      end
    end

    def decade_dates
      return [] unless date_value

      dates = DateDecadeConverter.new(date_value).run
      dates ||= Array.wrap(DecadeDecorator.new(parsed_year)) if parsed_year
      dates || []
    end

    def parsed_year
      clean_datetime&.year
    end

    def clean_datetime
      case date_value
      when /^[0-9]{4}-[0-9]{2}-[0-9]{2}$/ # YYYY-MM-DD
        DateTime.strptime(date_value, '%Y-%m-%d')
      when /^[0-9]{4}-[0-9]{2}$/ # YYYY-MM
        DateTime.strptime(date_value, '%Y-%m')
      when /^[0-9]{4}/ # YYYY
        DateTime.strptime(date_value.split('-').first, '%Y')
      else
        Rails.logger.warn "Invalid date_value: #{date_value}. Acceptable formats: YYYY-MM-DD, YYYY-MM, YYYY."
        nil
      end
    end

    # Date decorator
    class DecadeDecorator
      attr_accessor :year

      def initialize(year)
        @year = year
      end

      def decade
        "#{first_year}-#{last_year}"
      end

      private

      def first_year
        year - year % 10
      end

      def last_year
        year + 10 - (year + 10) % 10 - 1
      end
    end

    # Used for processing decades given a date and generates an array of decorated items using DecadeDecorator
    # when calling run. Expected input dates: "2017-12-01", "2017-12", "2017", "2017-2018", "2010-2020", "1900-1940"
    class DateDecadeConverter
      attr_accessor :date

      def initialize(date)
        @date = date
      end

      def run
        return unless valid_date_range?

        decades.times.map do |decade|
          DecadeDecorator.new(earliest_date + 10 * decade)
        end
      end

      private

      def earliest_date
        @earliest_date ||= dates.first - dates.first % 10
      end

      def valid_decade_size?
        decades <= 3
      end

      def valid_date_range?
        dates.first.to_s.length == 4 && dates.last.to_s.length == 4 && dates.length == 2
      end

      def dates
        @dates ||= date.to_s.split('-').map(&:to_i)
      end

      def decades
        calculated_decades = (dates.last - dates.first) / 10 + 1
        calculated_decades <= 3 ? calculated_decades : 0
      end
    end
  end
end

app/models/concerns/scholars_archive/etd_metadata.rb
# frozen_string_literal: true

module ScholarsArchive
  # etd metadata
  module EtdMetadata
    extend ActiveSupport::Concern

    # Usage notes and expectations can be found in the Metadata Application Profile:
    #   https://docs.google.com/spreadsheets/d/1koKjV7bjn7v4r5a3gsowEimljHiAwbwuOgjHe7FEtuw/edit?usp=sharing

    included do
      property :contributor_committeemember, predicate: ::RDF::Vocab::MARCRelators.dgs do |index|
        index.as :stored_searchable, :facetable
      end

      property :degree_discipline, predicate: ::RDF::URI.new('http://http://dbpedia.org/ontology/academicDiscipline') do |index|
        index.as :stored_searchable
      end

      property :degree_grantors, predicate: ::RDF::Vocab::MARCRelators.dgg, multiple: false do |index|
        index.as :stored_searchable
      end

      # accessor value used by AddOtherFieldOptionActor to persist "Other" values provided by the user
      attr_accessor :degree_grantors_other

      property :graduation_year, predicate: ::RDF::URI.new('http://www.rdaregistry.info/Elements/w/#P10215'), multiple: false do |index|
        index.as :stored_searchable, :facetable
      end
    end
  end
end

app/models/concerns/scholars_archive/excluded_article_licenses.rb
# frozen_string_literal: true

module ScholarsArchive
  # excluded article licenses
  module ExcludedArticleLicenses
    extend ActiveSupport::Concern

    included do
      def excluded_licenses
        []
      end
    end
  end
end

app/models/concerns/scholars_archive/excluded_default_licenses.rb
# frozen_string_literal: true

module ScholarsArchive
  # excluded licenses
  module ExcludedDefaultLicenses
    extend ActiveSupport::Concern

    included do
      def excluded_licenses
        []
      end
    end
  end
end

app/models/concerns/scholars_archive/excluded_etd_licenses.rb
# frozen_string_literal: true

module ScholarsArchive
  # excluded licenses
  module ExcludedEtdLicenses
    extend ActiveSupport::Concern

    included do
      def excluded_licenses
        ['CC0 1.0 Universal']
      end
    end
  end
end

app/models/concerns/scholars_archive/excluded_oer_licenses.rb
# frozen_string_literal: true

module ScholarsArchive
  # excluded licenses
  module ExcludedOerLicenses
    extend ActiveSupport::Concern

    included do
      def excluded_licenses
        []
      end
    end
  end
end

app/models/concerns/scholars_archive/file_set/indexing.rb
module ScholarsArchive
  module FileSet
    module Indexing
      extend ActiveSupport::Concern

      included do
        # the default indexing service
        self.indexer = FileSetIndexer
      end
    end
  end
end

app/models/concerns/scholars_archive/file_set_behavior.rb
module ScholarsArchive
  module FileSetBehavior
    extend ActiveSupport::Concern
    include Hyrax::WithEvents
    include Hydra::Works::FileSetBehavior
    include Hydra::Works::VirusCheck
    include Hyrax::FileSet::Characterization
    include Hydra::WithDepositor
    include Hyrax::Serializers
    include Hyrax::Noid
    include Hyrax::FileSet::Derivatives
    include Hyrax::Permissions
    include ScholarsArchive::FileSet::Indexing
    include Hyrax::FileSet::BelongsToWorks
    include Hyrax::FileSet::Querying
    include Hyrax::HumanReadableType
    include Hyrax::CoreMetadata
    include Hyrax::BasicMetadata
    include Hyrax::Naming
    include Hydra::AccessControls::Embargoable
    include GlobalID::Identification

    included do
      attr_accessor :file
    end

    def representative_id
      to_param
    end

    def thumbnail_id
      to_param
    end

    # Cast to a SolrDocument by querying from Solr
    def to_presenter
      CatalogController.new.fetch(id).last
    end
  end
end

app/models/concerns/scholars_archive/finalize_nested_metadata.rb
# frozen_string_literal: true

module ScholarsArchive
  # Finalize default metadata. This was split from ScholarsArchive::DefaultMetadata because FileSets need to call these AFTER ::Hyrax::FileSetBehavior is included
  # But properties from ::ScholarsArchive::DefaultMetadata needs to be defined BEFORE ::Hyrax::FileSetBehavior is included (because it calls accepts_nested_attributes_for)
  module FinalizeNestedMetadata
    extend ActiveSupport::Concern

    # Usage notes and expectations can be found in the Metadata Application Profile:
    #   https://docs.google.com/spreadsheets/d/1koKjV7bjn7v4r5a3gsowEimljHiAwbwuOgjHe7FEtuw/edit?usp=sharing

    included do
      accepts_nested_attributes_for :based_near, allow_destroy: true, reject_if: proc { |a| a[:id].blank? }
      accepts_nested_attributes_for :funding_body, allow_destroy: true, reject_if: proc { |a| a[:id].blank? }
      accepts_nested_attributes_for :nested_geo, allow_destroy: true, reject_if: :all_blank
      accepts_nested_attributes_for :nested_related_items, allow_destroy: true, reject_if: :all_blank
      # reject if all attributes all blank OR if either index or creator is blank
      accepts_nested_attributes_for :nested_ordered_title, allow_destroy: true, reject_if: proc { |attributes| attributes[:title].blank? || attributes.all? { |key, value| key == '_destroy' || value.blank? } }
      accepts_nested_attributes_for :nested_ordered_creator, allow_destroy: true, reject_if: proc { |attributes| attributes[:creator].blank? || attributes.all? { |key, value| key == '_destroy' || value.blank? } }
      accepts_nested_attributes_for :nested_ordered_abstract, allow_destroy: true, reject_if: proc { |attributes| attributes[:abstract].blank? || attributes.all? { |key, value| key == '_destroy' || value.blank? } }
      accepts_nested_attributes_for :nested_ordered_contributor, allow_destroy: true, reject_if: proc { |attributes| attributes[:contributor].blank? || attributes.all? { |key, value| key == '_destroy' || value.blank? } }
      accepts_nested_attributes_for :nested_ordered_additional_information, allow_destroy: true, reject_if: proc { |attributes| attributes[:additional_information].blank? || attributes.all? { |key, value| key == '_destroy' || value.blank? } }
    end
  end
end

app/views/scholars_archive/accessibility_request_form/new.html.erb
<h1>
    <%= t('hyrax.accessibility_request_form.header') %>
</h1>

<p>
  ScholarsArchive@OSU has long accepted scholarly content from the OSU community in many formats. We are aware that not all items in the repository are fully accessible to all of our users at this time, and we are working hard to bring all content up to the standards outlined in <a href="https://policy.oregonstate.edu/policy/digital-accessibility" target="_blank">OSU's Digital Accessibility Policy</a>.
  <br/><br/>
  To request a remediated version of inaccessible content, such as a PDF document or media file, please complete the form below and OSU Libraries staff will accommodate your request. Some types of remediation take a substantial amount of staff time, so please give as much advance notice as possible.
  <br/><br/>
  If you are looking for help with a different topic in ScholarsArchive@OSU, use the <a href="<%= hyrax.contact_form_index_path %>" target="_blank">Contact Us</a> form.
</p>

<br/>

<h2>
    <%= t('hyrax.accessibility_request_form.sub_header') %>
</h2>
<p>
  Fields marked with <span style="color:red"> * </span> are required.
</p>

<%# FORM: Create the form view page to submit the accessibility form %>
<%= form_for @accessibility_form, url: accessibility_request_form_index_path,
                            html: { class: 'form-horizontal' } do |f| %>
  <%# HIDDEN FIELD: This field is hidden to check for spam %>
  <%= f.text_field :accessibility_method, class: 'hide' %>

  <%# NAME: Set the naming box %>
  <div class="form-group">
    <p> <%= f.label :name, t('hyrax.accessibility_request_form.name'), class: "control-label", id: "name-label" %> <span style="color:red"> * </span> </p>
    <div class="accessibility-name"><%= f.text_field :name, value: user_signed_in? ? current_user.name : '', class: 'form-control', required: true, 'aria-required': "true", 'aria-labelledby': "name-label" %></div>
  </div>

  <%# EMAIL: Set the email layout to enter in email, if login use their email %>
  <div class="form-group">
    <p> <%= f.label :email, t('hyrax.accessibility_request_form.email'), class: "control-label", id: "email-label" %> <span style="color:red"> * </span> </p>
    <div class="accessibility-email"><%= f.text_field :email, value: user_signed_in? ? current_user.email : '', class: 'form-control', required: true, 'aria-required': "true", 'aria-labelledby': "email-label" %></div>
  </div>

  <%# CONFIRM EMAIL: Set the email layout to enter again to confirm if the email is correct %>
  <div class="form-group">
    <p> <%= f.label :confirm_email, t('hyrax.accessibility_request_form.confirm_email'), class: "control-label", id: "confirm-email-label" %> <span style="color:red"> * </span> </p>
    <div class="accessibility-email"><%= f.text_field :confirm_email, value: '', class: 'form-control', required: true, 'aria-required': "true", 'aria-labelledby': "confirm-email-label" %></div>
  </div>

  <%# PHONE: Provide the phone number option %>
  <div class="form-group">
    <%= f.label :phone, t('hyrax.accessibility_request_form.phone'), class: "control-label", id: "phone-label" %>
    <div class="accessibility-phone"><%= f.text_field :phone, value: '', class: 'form-control', 'aria-labelledby': "phone-label" %></div>
  </div>

  <%# LINK: Provide the link to let user gives the link to access accessibility %>
  <div class="form-group">
    <p> <%= f.label :url_link, t('hyrax.accessibility_request_form.link'), class: "control-label" %> <span style="color:red"> * </span> </p>
    <div class="accessibility-url-link"><%= f.url_field :url_link, value: @request_url.blank? ? @accessibility_form.url_link : @request_url, class: 'form-control', required: true, 'aria-required': "true", 'aria-labelledby': "url-label" %></div>
    <p id="url-label"><em>Please include the full link to the item that you would like us to remediate.</em></p>
  </div>

  <%# DESCRIPTION: Provide the detail about the accessibility %>
  <div class="form-group">
    <p> <%= f.label :details, t('hyrax.accessibility_request_form.details'), class: "control-label" %> <span style="color:red"> * </span> </p>
    <div class="accessibility-details"><%= f.text_area :details, value: '', rows: 4, class: 'form-control', required: true, 'aria-required': "true", 'aria-labelledby': "desc-label" %></div>
    <p id="desc-label"><em>Please describe the type of accommodation that you need (for example, written transcription, compatibility with a particular assistive device, preferred file formats, etc.). Documents will be provided in Microsoft Word format unless otherwise noted. Include details about what particular parts of the content are inaccessible, if applicable.</em></p>
  </div>

  <%# DESCRIPTION: Provide the additional detail about the accessibility %>
  <div class="form-group">
    <%= f.label :additional, t('hyrax.accessibility_request_form.additional'), class: "control-label" %>
    <div class="accessibility-additional"><%= f.text_area :additional, value: '', rows: 4, class: 'form-control', 'aria-labelledby': "addi-label" %></div>
    <p id="addi-label"><em>List any other ScholarsArchive@OSU items you would like remediated as part of this request.</em></p>
  </div>

  <%# DATE: Provide the date needed for request %>
  <div class="form-group">
    <%= f.label :date, t('hyrax.accessibility_request_form.date'), class: "control-label" %>
    <div class="accessibility-date"><%= f.date_field :date, value: f.object.try(:strftime,"%m/%d/%Y"), class: 'form-control', 'aria-labelledby': "date-label" %></div>
    <p id="date-label"><em>If you need this item by a particular date, let us know and we will do our best to deliver by your deadline.</em></p>
  </div>

  <%# CAPTCHA: Add in the captcha on form %>
  <%= recaptcha_tags if Hyrax.config.recaptcha? %>
  <%= invisible_captcha %>
  <%= f.submit value: t('hyrax.accessibility_request_form.button'), class: "btn btn-primary", 'aria-label': "Send" %>
<% end %>